name: ar6-wg1
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip>=21.0
  - iris<3.0
  - ipywidgets
  - feather-format==0.4.1
  - nb_black==1.0.7
  - netcdf4==1.5.6
  - pymagicc==2.0.0
  - scmdata==0.9.1
  - seaborn==0.11.1
  - pytables==3.6.1
  - pip:
    - nbdime==2.1.0
    - nbresuse==0.4.0
    - netcdf-scm==2.1.0
